<?php

namespace Database\Seeders;

use App\Models\Meal;
use Illuminate\Database\Seeder;

class FilipinoMealsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $filipinoMeals = [
            // Rice Meals - Affordable and filling
            [
                'name' => 'Adobong Manok',
                'description' => 'Classic Filipino chicken adobo with rice. Tender chicken simmered in soy sauce, vinegar, and garlic.',
                'category' => 'Rice Meals',
                'price' => 65.00,
                'calories' => 520,
                'protein' => 35,
                'carbs' => 45,
                'fat' => 18,
                'prep_time' => 45,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Gluten-Free'],
                'is_featured' => true,
            ],
            [
                'name' => 'Adobong Baboy',
                'description' => 'Filipino pork adobo with steamed rice. Rich and savory pork belly in traditional adobo sauce.',
                'category' => 'Rice Meals',
                'price' => 75.00,
                'calories' => 650,
                'protein' => 40,
                'carbs' => 48,
                'fat' => 28,
                'prep_time' => 60,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Gluten-Free'],
                'is_featured' => true,
            ],
            [
                'name' => 'Ginisang Monggo',
                'description' => 'Filipino mung bean stew with rice. Healthy and budget-friendly comfort food perfect for students.',
                'category' => 'Rice Meals',
                'price' => 45.00,
                'calories' => 380,
                'protein' => 18,
                'carbs' => 55,
                'fat' => 8,
                'prep_time' => 30,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Vegetarian', 'High-Protein'],
                'is_featured' => false,
            ],
            [
                'name' => 'Pork Sisig',
                'description' => 'Sizzling pork sisig with rice. Crispy pork belly and ears with onions, perfect with a cold drink.',
                'category' => 'Rice Meals',
                'price' => 85.00,
                'calories' => 720,
                'protein' => 42,
                'carbs' => 35,
                'fat' => 45,
                'prep_time' => 40,
                'difficulty' => 'Medium',
                'dietary_tags' => ['High-Protein'],
                'is_featured' => true,
            ],
            [
                'name' => 'Chicken Curry',
                'description' => 'Filipino-style chicken curry with coconut milk and potatoes. Mild and creamy curry served with rice.',
                'category' => 'Rice Meals',
                'price' => 70.00,
                'calories' => 580,
                'protein' => 38,
                'carbs' => 42,
                'fat' => 25,
                'prep_time' => 50,
                'difficulty' => 'Medium',
                'dietary_tags' => ['Gluten-Free'],
                'is_featured' => false,
            ],

            // Noodle Dishes
            [
                'name' => 'Pancit Canton',
                'description' => 'Filipino stir-fried egg noodles with vegetables and meat. A student favorite thats filling and affordable.',
                'category' => 'Noodles',
                'price' => 55.00,
                'calories' => 460,
                'protein' => 22,
                'carbs' => 65,
                'fat' => 12,
                'prep_time' => 25,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Quick-Meal'],
                'is_featured' => true,
            ],
            [
                'name' => 'Pancit Bihon',
                'description' => 'Thin rice noodles stir-fried with vegetables and shrimp or chicken. Light but satisfying meal.',
                'category' => 'Noodles',
                'price' => 50.00,
                'calories' => 420,
                'protein' => 18,
                'carbs' => 68,
                'fat' => 8,
                'prep_time' => 20,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Gluten-Free', 'Quick-Meal'],
                'is_featured' => false,
            ],
            [
                'name' => 'Lomi',
                'description' => 'Thick egg noodle soup with meat and vegetables. Perfect comfort food for rainy days.',
                'category' => 'Noodles',
                'price' => 60.00,
                'calories' => 510,
                'protein' => 25,
                'carbs' => 58,
                'fat' => 18,
                'prep_time' => 35,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Comfort-Food'],
                'is_featured' => false,
            ],

            // Affordable Breakfast
            [
                'name' => 'Tapsilog',
                'description' => 'Filipino beef jerky with garlic rice and fried egg. Classic Filipino breakfast combo.',
                'category' => 'Breakfast',
                'price' => 80.00,
                'calories' => 620,
                'protein' => 35,
                'carbs' => 48,
                'fat' => 28,
                'prep_time' => 20,
                'difficulty' => 'Easy',
                'dietary_tags' => ['High-Protein', 'Breakfast'],
                'is_featured' => true,
            ],
            [
                'name' => 'Longsilog',
                'description' => 'Filipino sweet sausage with garlic rice and fried egg. Sweet and savory breakfast favorite.',
                'category' => 'Breakfast',
                'price' => 75.00,
                'calories' => 580,
                'protein' => 28,
                'carbs' => 52,
                'fat' => 25,
                'prep_time' => 15,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Breakfast', 'Quick-Meal'],
                'is_featured' => false,
            ],
            [
                'name' => 'Bangsilog',
                'description' => 'Fried milkfish with garlic rice and fried egg. Healthy fish breakfast option.',
                'category' => 'Breakfast',
                'price' => 85.00,
                'calories' => 540,
                'protein' => 42,
                'carbs' => 45,
                'fat' => 18,
                'prep_time' => 25,
                'difficulty' => 'Medium',
                'dietary_tags' => ['High-Protein', 'Breakfast'],
                'is_featured' => false,
            ],

            // Snacks and Light Meals
            [
                'name' => 'Palabok',
                'description' => 'Rice noodles with shrimp sauce, topped with shrimp, eggs, and chicharon. Filipino comfort food.',
                'category' => 'Snacks',
                'price' => 55.00,
                'calories' => 440,
                'protein' => 20,
                'carbs' => 62,
                'fat' => 12,
                'prep_time' => 30,
                'difficulty' => 'Medium',
                'dietary_tags' => ['Comfort-Food'],
                'is_featured' => true,
            ],
            [
                'name' => 'Lumpia Shanghai',
                'description' => 'Crispy Filipino spring rolls filled with ground pork and vegetables. Perfect for sharing.',
                'category' => 'Snacks',
                'price' => 40.00,
                'calories' => 320,
                'protein' => 15,
                'carbs' => 28,
                'fat' => 18,
                'prep_time' => 45,
                'difficulty' => 'Medium',
                'dietary_tags' => ['Finger-Food'],
                'is_featured' => false,
            ],
            [
                'name' => 'Pork BBQ',
                'description' => 'Grilled pork skewers with sweet marinade. Popular Filipino street food, perfect with rice.',
                'category' => 'Snacks',
                'price' => 25.00,
                'calories' => 180,
                'protein' => 18,
                'carbs' => 8,
                'fat' => 9,
                'prep_time' => 20,
                'difficulty' => 'Easy',
                'dietary_tags' => ['High-Protein', 'Street-Food'],
                'is_featured' => false,
            ],

            // Vegetable Dishes
            [
                'name' => 'Pinakbet',
                'description' => 'Mixed vegetables stewed in shrimp paste. Healthy and affordable Filipino vegetable dish.',
                'category' => 'Vegetables',
                'price' => 50.00,
                'calories' => 220,
                'protein' => 8,
                'carbs' => 35,
                'fat' => 6,
                'prep_time' => 25,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Healthy', 'Low-Calorie'],
                'is_featured' => false,
            ],
            [
                'name' => 'Ginisang Sayote',
                'description' => 'Sautéed chayote with ground meat. Simple and nutritious dish perfect for students on a budget.',
                'category' => 'Vegetables',
                'price' => 35.00,
                'calories' => 180,
                'protein' => 12,
                'carbs' => 18,
                'fat' => 6,
                'prep_time' => 15,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Budget-Friendly', 'Healthy'],
                'is_featured' => false,
            ],

            // Soup Dishes
            [
                'name' => 'Sinigang na Baboy',
                'description' => 'Sour pork soup with vegetables. Filipino comfort soup perfect for sharing and budget-friendly.',
                'category' => 'Soup',
                'price' => 70.00,
                'calories' => 380,
                'protein' => 28,
                'carbs' => 25,
                'fat' => 18,
                'prep_time' => 50,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Comfort-Food', 'Healthy'],
                'is_featured' => true,
            ],
            [
                'name' => 'Tinola',
                'description' => 'Chicken soup with ginger, green papaya, and chili leaves. Light and healthy Filipino soup.',
                'category' => 'Soup',
                'price' => 65.00,
                'calories' => 320,
                'protein' => 25,
                'carbs' => 20,
                'fat' => 12,
                'prep_time' => 40,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Healthy', 'Low-Calorie'],
                'is_featured' => false,
            ],

            // Budget Rice Toppings
            [
                'name' => 'Pork Tocino',
                'description' => 'Sweet cured pork served with rice. Filipino breakfast favorite thats affordable and filling.',
                'category' => 'Rice Meals',
                'price' => 60.00,
                'calories' => 520,
                'protein' => 30,
                'carbs' => 45,
                'fat' => 22,
                'prep_time' => 20,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Quick-Meal', 'Breakfast'],
                'is_featured' => false,
            ],
            [
                'name' => 'Corned Beef',
                'description' => 'Filipino-style corned beef with onions and potatoes. Quick and easy meal for busy students.',
                'category' => 'Rice Meals',
                'price' => 55.00,
                'calories' => 460,
                'protein' => 26,
                'carbs' => 40,
                'fat' => 20,
                'prep_time' => 15,
                'difficulty' => 'Easy',
                'dietary_tags' => ['Quick-Meal', 'Budget-Friendly'],
                'is_featured' => false,
            ],
        ];

        foreach ($filipinoMeals as $meal) {
            Meal::create($meal);
        }
    }
}
